---
DATADOG_API_KEY: "SPECIFY_KEY_HERE"

DATADOG_SITE: datadoghq.com

DATADOG_AGENT_VERSION: '1:7.50.3-1'

datadog_user: "dd-agent"

# Variables for Datadog MongoDB Monitoring
datadog_mongo_host: 127.0.0.1
datadog_mongo_port: 27017
datadog_mongo_username: datadog
datadog_mongo_password: password
datadog_mongo_db: admin
datadog_authsource_db: admin

datadog_apt_key: "0xAD9589B7"
datadog_debian_pkgs:
  - apt-transport-https 
  - curl 
  - gnupg

DATADOG_MONGODB_MONITORING: false
